version: 0.0.1
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11.10.1-stretch

    working_directory: ~/repo/Coursework_ToDo

    steps:
      - checkout

      - run:
          name: Preparing
          command: |
            sudo npm i -g yarn
            yarn install
            yarn build
      - run:
          name: Deploying
          command: |
            zip -r coursework.zip ./
            scp -oStrictHostKeyChecking=no beejee-test-task.zip ${ssh_connection}:beejee-test-task.zip;
            scp -oStrictHostKeyChecking=no install.sh ${ssh_connection}:install.sh;
            ssh -oStrictHostKeyChecking=no ${ssh_connection} <<< $'./install.sh';
